### ISSUE TITLE
Unexpected token '<'

### ISSUE THREAD

**Issue by renjith01** [fnakstad/angular-client-side-auth#67] opened 2014-02-27 14:33 UTC
Let me thank you first for this implementation, but I am getting SyntaxError: Unexpected token '<' in the browser console while trying to run locally. Tried both in bot mac and windows. Am I missing something?

**Comment by fnakstad** [comment] 2014-02-28 01:49
Hi! I can't seem to reproduce your problem. Are you using a clean build or are there local changes in your repo? Does this happen as soon as you open the web app in the browser? Any error messages in the server console?

**Comment by geyang** [comment] 2014-02-28 09:08
Yeah, this is a typical problem when one of your resources defined in the
index.html file is missing.

If you check the console.log in your server terminal, you might be able to
figure out which one is missing. The missing one should have a 404 status
code, while all the other ones are either 200 or 304 (cached).

Ge

**Comment by geyang** [comment] 2014-02-28 09:10
Hey fnakstad,

Do you think this might be the underscore.js file? I remember that from the
message from the other pull-reuest from yesterday.

Ge

**Comment by renjith01** [comment] 2014-02-28 09:59
I don't find anything in 404 status. I am able to reproduce the issue in a new installation. Not sure ii the issue is due to bower caches. I was able to install one instance successfully after I manually installed some components which was not fetched by npm install command yesterday like supertest, passport stub and karma-chai . But I am not able to reproduce the success scenario again. I had used npm set strict-ssl false also also npm install --unsafe-perm
logs in console
uncaught SyntaxError: Unexpected token < angular.min.js:1
Uncaught SyntaxError: Unexpected token < angular-cookies.min.js:1
Uncaught SyntaxError: Unexpected token < angular-ui-router.min.js:1
Uncaught ReferenceError: angular is not defined app.js:3
Uncaught ReferenceError: angular is not defined services.js:3
Uncaught ReferenceError: angular is not defined controllers.js:5
Uncaught ReferenceError: angular is not defined directives.js:3

**Comment by geyang** [comment] 2014-02-28 10:11
I think your error messages suggest that your angular.min.js is missing,
angular-cookies is missing, angular-ui-router is missing.

Can you check if those are accessible in a browser?

Ge

**Comment by fnakstad** [comment] 2014-03-02 01:25
Yea, my guess is that something goes wrong when fetching dependencies with bower. Could you check if the client/components folder exists and if it contains the packages defined in `bower.json`? If this is the case you can try running `bower install` to fetch them again.

**Comment by jshemas** [comment] 2014-03-04 04:02
I'm getting the same problem, but running `bower install` seemed to fix it.

**Comment by fnakstad** [comment] 2014-03-04 04:20
Hmmm, I see... I tried adding `bower install` as a postinstall script to `npm install`, so that you only have to execute one command instead of two to install dependencies. However it seems many of you are having trouble with it... Could any of you guys experiencing this problem try executing `grunt clean`, and then `npm install` to see if the problem persists?

**Comment by austinpray** [comment] 2014-03-04 04:22
> I tried adding bower install as a postinstall script to npm install

YOU CAN DO THAT????
༼ つ ◕_◕ ༽つ fnakstad ༼ つ ◕_◕ ༽つ

**Comment by fnakstad** [comment] 2014-03-04 04:39
Well, now that people are reporting problems I'm not so sure anymore, but [this](https://github.com/fnakstad/angular-client-side-auth/blob/master/package.json#L26) works for me :)
Note that you need to add bower as a dependency in npm, so you can use a local install of it in case it's not installed globally.

**Comment by fnakstad** [comment] 2014-03-16 05:05
Reverted to relying on global install of bower, so I'll go ahead and close this.

**Closed as completed by fnakstad** 2014-03-16 05:05 UTC

**Comment by austinpray** [comment] 2014-03-16 05:07
Global install is a common pattern anyway. No need for duplicate bower binaries

**Comment by brunaobh** [comment] 2014-09-12 18:24
bower install.. fix the problem here

**Comment by ghost** [comment] 2015-05-27 18:36
I have been fighting this problem for a few hours and finally noticed something not mentioned previously (Here or at SO)...
In ASP.NET/MVC application this error (Unexpected token '<' ) can result from attempting to call
@Scripts.Render("...") on a non-existent bundle. 

D'OH

**Comment by AskYous** [comment] 2016-01-21 21:58
I received this issue as well just now. Though, the problem with mine was that I typed an incorrect URL:

`index.html/#/` gives the error. `index.html#/` solved it.

**Comment by garvitsharma** [comment] 2016-07-18 09:39
I think your error messages suggest that your angular.min.js is missing,

**Comment by divya12prakash** [comment] 2017-09-10 02:22
I am using angular 4, but even after re-installing the dependencies through npm or other suggestions do not work for me

**Comment by SeaCatWiz** [comment] 2018-01-06 04:57
I had the same problem. And no any 404 errors. But it was actually missing file. It looked like files have been downloaded but actually, Node.js server downloaded some default page instead of them. It turned out I screwed up with paths. Why server exposed such behavior I don't know. As soon as I add "base" to the header everything was fixed.

**Comment by Mujtaba81** [comment] 2018-02-20 19:28
I am getting this error both locally as well as while using cloud IDE c9.io

"Uncaught SyntaxError: Unexpected token <"

**Comment by SeaCatWiz** [comment] 2018-02-20 19:34
Mujtaba81, looks like you have a missing file too. I'm pretty sure if you look at your response in Chrome you will see the HTML of 404 error, not JavaScript, that's why you have this error.
